
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package test;

/** CUP generated class containing symbol constants. */
public class ParserSym {
  /* terminals */
  public static final int INT = 8;
  public static final int MENOS = 3;
  public static final int EOF = 0;
  public static final int MAS = 2;
  public static final int DIV = 5;
  public static final int error = 1;
  public static final int RPAREN = 7;
  public static final int MUL = 4;
  public static final int LPAREN = 6;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "MAS",
  "MENOS",
  "MUL",
  "DIV",
  "LPAREN",
  "RPAREN",
  "INT"
  };
}

