
import java.awt.Color;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import tipografias.Fuentes;


/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Alex
 */

public class VentanaBienvenida extends javax.swing.JFrame {
    Fuentes tipoFuente;
    /**
     * Creates new form NewJFrame
     */
    public VentanaBienvenida() {
        initComponents();
        setLocationRelativeTo(null); //Centrar
        
        //Declaración y uso de fuentes
        tipoFuente = new Fuentes();
        lblArchivo.setFont(tipoFuente.fuente(tipoFuente.INTER,0,15));
        lblTitulo.setFont(tipoFuente.fuente(tipoFuente.INTER,0,30));
        lblEditar.setFont(tipoFuente.fuente(tipoFuente.INTER,0,15));
        lblSeleccion.setFont(tipoFuente.fuente(tipoFuente.INTER,0,15));
        lblAyuda.setFont(tipoFuente.fuente(tipoFuente.INTER,0,15));
        lblAyuda1.setFont(tipoFuente.fuente(tipoFuente.INTER,0,15));
        lblTitulo1.setFont(tipoFuente.fuente(tipoFuente.INTER,0,15));
        lblTitulo2.setFont(tipoFuente.fuente(tipoFuente.INTER,0,15));
        lblTitulo3.setFont(tipoFuente.fuente(tipoFuente.INTER,0,15));
        lblTitulo4.setFont(tipoFuente.fuente(tipoFuente.INTER,0,15));
        lblTitulo5.setFont(tipoFuente.fuente(tipoFuente.INTER,0,15));
        btnOpen.setFont(tipoFuente.fuente(tipoFuente.INTER,0,14));
        btnNew.setFont(tipoFuente.fuente(tipoFuente.INTER,0,14));
        btnCompile.setFont(tipoFuente.fuente(tipoFuente.INTER,0,14));
        btnSave.setFont(tipoFuente.fuente(tipoFuente.INTER,0,14));
        
        
       //Icono programa
       setIconImage(new ImageIcon(getClass().getResource("/images/logo-png.png")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jpnSuperior = new javax.swing.JPanel();
        lblArchivo = new javax.swing.JLabel();
        lblSeleccion = new javax.swing.JLabel();
        lblEditar = new javax.swing.JLabel();
        lblAyuda = new javax.swing.JLabel();
        lblMinimizar = new javax.swing.JLabel();
        lblCentrar = new javax.swing.JLabel();
        lblCerrar = new javax.swing.JLabel();
        lbl_Icono = new javax.swing.JLabel();
        lblAyuda1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnOpen = new javax.swing.JButton();
        btnNew = new javax.swing.JButton();
        btnCompile = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        lblTitulo2 = new javax.swing.JLabel();
        lblTitulo3 = new javax.swing.JLabel();
        lblTitulo4 = new javax.swing.JLabel();
        lblTitulo5 = new javax.swing.JLabel();
        lblTitulo1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jpnSuperior.setBackground(new java.awt.Color(81, 90, 92));

        lblArchivo.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblArchivo.setForeground(new java.awt.Color(255, 255, 255));
        lblArchivo.setText("Archivo");

        lblSeleccion.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblSeleccion.setForeground(new java.awt.Color(255, 255, 255));
        lblSeleccion.setText("Selección");

        lblEditar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblEditar.setForeground(new java.awt.Color(255, 255, 255));
        lblEditar.setText("Editar");

        lblAyuda.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblAyuda.setForeground(new java.awt.Color(255, 255, 255));
        lblAyuda.setText("Ayuda");
        lblAyuda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAyudaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblAyudaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblAyudaMouseExited(evt);
            }
        });
        lblAyuda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                lblAyudaKeyPressed(evt);
            }
        });

        lblMinimizar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblMinimizar.setForeground(new java.awt.Color(255, 255, 255));
        lblMinimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/min.png"))); // NOI18N

        lblCentrar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblCentrar.setForeground(new java.awt.Color(255, 255, 255));
        lblCentrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/centrar.png"))); // NOI18N

        lblCerrar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblCerrar.setForeground(new java.awt.Color(255, 255, 255));
        lblCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/exit.png"))); // NOI18N
        lblCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCerrarMouseClicked(evt);
            }
        });

        lbl_Icono.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lbl_Icono.setForeground(new java.awt.Color(255, 255, 255));
        lbl_Icono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logopng2.png"))); // NOI18N

        lblAyuda1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblAyuda1.setForeground(new java.awt.Color(255, 255, 255));
        lblAyuda1.setText("RoboKit");

        javax.swing.GroupLayout jpnSuperiorLayout = new javax.swing.GroupLayout(jpnSuperior);
        jpnSuperior.setLayout(jpnSuperiorLayout);
        jpnSuperiorLayout.setHorizontalGroup(
            jpnSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnSuperiorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_Icono)
                .addGap(40, 40, 40)
                .addComponent(lblArchivo)
                .addGap(50, 50, 50)
                .addComponent(lblEditar)
                .addGap(50, 50, 50)
                .addComponent(lblSeleccion)
                .addGap(41, 41, 41)
                .addComponent(lblAyuda)
                .addGap(248, 248, 248)
                .addComponent(lblAyuda1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 480, Short.MAX_VALUE)
                .addComponent(lblMinimizar)
                .addGap(26, 26, 26)
                .addComponent(lblCentrar)
                .addGap(18, 18, 18)
                .addComponent(lblCerrar)
                .addGap(26, 26, 26))
        );
        jpnSuperiorLayout.setVerticalGroup(
            jpnSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnSuperiorLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jpnSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblArchivo)
                    .addComponent(lblSeleccion)
                    .addComponent(lblEditar)
                    .addComponent(lblAyuda)
                    .addComponent(lblMinimizar)
                    .addComponent(lblCentrar)
                    .addComponent(lblCerrar)
                    .addComponent(lbl_Icono)
                    .addComponent(lblAyuda1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jpnSuperior, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1350, -1));

        jPanel2.setBackground(new java.awt.Color(233, 231, 231));

        btnOpen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/open-file.png"))); // NOI18N
        btnOpen.setText("Abrir");

        btnNew.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add.png"))); // NOI18N
        btnNew.setText("Nuevo");
        btnNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewActionPerformed(evt);
            }
        });

        btnCompile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/compile.png"))); // NOI18N
        btnCompile.setText("Compilar");

        btnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/save.png"))); // NOI18N
        btnSave.setText("Guardar");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(btnNew, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(btnOpen, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(btnCompile, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(698, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnSave, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCompile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(btnOpen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnNew, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 1350, 50));

        jPanel3.setBackground(new java.awt.Color(207, 206, 212));

        lblTitulo.setBackground(new java.awt.Color(0, 0, 0));
        lblTitulo.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        lblTitulo.setText("Bienvenido a RoboKit IDE");

        lblTitulo2.setBackground(new java.awt.Color(0, 0, 0));
        lblTitulo2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTitulo2.setText("A programar!");

        lblTitulo3.setBackground(new java.awt.Color(0, 0, 0));
        lblTitulo3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTitulo3.setForeground(new java.awt.Color(133, 46, 186));
        lblTitulo3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add.png"))); // NOI18N
        lblTitulo3.setText("Crear un nuevo archivo");

        lblTitulo4.setBackground(new java.awt.Color(0, 0, 0));
        lblTitulo4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTitulo4.setForeground(new java.awt.Color(133, 46, 186));
        lblTitulo4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/open-file.png"))); // NOI18N
        lblTitulo4.setText("Abrir un archivo");

        lblTitulo5.setBackground(new java.awt.Color(0, 0, 0));
        lblTitulo5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTitulo5.setForeground(new java.awt.Color(133, 46, 186));
        lblTitulo5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/folder.png"))); // NOI18N
        lblTitulo5.setText("Abrir una carpeta");

        lblTitulo1.setBackground(new java.awt.Color(0, 0, 0));
        lblTitulo1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTitulo1.setForeground(new java.awt.Color(133, 46, 186));
        lblTitulo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/about.png"))); // NOI18N
        lblTitulo1.setText("Acerca de RoboKit");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTitulo1)
                    .addComponent(lblTitulo3)
                    .addComponent(lblTitulo2)
                    .addComponent(lblTitulo)
                    .addComponent(lblTitulo4)
                    .addComponent(lblTitulo5))
                .addContainerGap(875, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(lblTitulo)
                .addGap(31, 31, 31)
                .addComponent(lblTitulo2)
                .addGap(41, 41, 41)
                .addComponent(lblTitulo3)
                .addGap(18, 18, 18)
                .addComponent(lblTitulo4)
                .addGap(22, 22, 22)
                .addComponent(lblTitulo5)
                .addGap(27, 27, 27)
                .addComponent(lblTitulo1)
                .addContainerGap(183, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 1330, 570));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 741, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNewActionPerformed

    private void lblAyudaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAyudaMouseEntered
        lblAyuda.setForeground(Color.red);
    }//GEN-LAST:event_lblAyudaMouseEntered

    private void lblAyudaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAyudaMouseExited
        lblAyuda.setForeground(Color.white);
    }//GEN-LAST:event_lblAyudaMouseExited

    private void lblAyudaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lblAyudaKeyPressed
        
    }//GEN-LAST:event_lblAyudaKeyPressed

    private void lblCerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCerrarMouseClicked
        System.exit(0);
    }//GEN-LAST:event_lblCerrarMouseClicked

    private void lblAyudaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAyudaMouseClicked
       JOptionPane.showMessageDialog(null,"Realizado por: \n Ibañez Parra Armando Jair\n Guzmán Álvarez Srgio Alejandro\n Manjarez Manzano Kevin Aziel ");
    }//GEN-LAST:event_lblAyudaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaBienvenida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaBienvenida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaBienvenida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaBienvenida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaBienvenida().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCompile;
    private javax.swing.JButton btnNew;
    private javax.swing.JButton btnOpen;
    private javax.swing.JButton btnSave;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jpnSuperior;
    private javax.swing.JLabel lblArchivo;
    private javax.swing.JLabel lblAyuda;
    private javax.swing.JLabel lblAyuda1;
    private javax.swing.JLabel lblCentrar;
    private javax.swing.JLabel lblCerrar;
    private javax.swing.JLabel lblEditar;
    private javax.swing.JLabel lblMinimizar;
    private javax.swing.JLabel lblSeleccion;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblTitulo1;
    private javax.swing.JLabel lblTitulo2;
    private javax.swing.JLabel lblTitulo3;
    private javax.swing.JLabel lblTitulo4;
    private javax.swing.JLabel lblTitulo5;
    private javax.swing.JLabel lbl_Icono;
    // End of variables declaration//GEN-END:variables
}
